### ISSUE TITLE
[1.16.4] Mod fails to load with AdoptOpenJDK OpenJ9 11.0.9 in Enigmatica6

### ISSUE THREAD

**Issue by telemenar** [vectorwing/FarmersDelight#115]
**Forge Version**
35.1.13

**Mod list (optional)**
Enigmatica6 0.3.2

**Log file (optional)**
```
-- MOD farmersdelight --
Details:
	Mod File: FarmersDelight-1.16.3-0.2.4b.jar
	Failure message: Farmer's Delight (farmersdelight) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: vectorwing.farmersdelight.FarmersDelight$$Lambda$6830/000000000000000000@e570e335
	Mod Version: 1.16.3-0.2.4b
	Mod Issue URL: https://github.com/vectorwing/FarmersDelight/issues
	Exception message: java.lang.IllegalStateException: Failed to resolve consumer event type: vectorwing.farmersdelight.FarmersDelight$$Lambda$6830/000000000000000000@e570e335
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.checkNotGeneric(EventBus.java:162) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:179) ~[eventbus-3.0.5-service.jar:?] {}
	at vectorwing.farmersdelight.FarmersDelight.<init>(FarmersDelight.java:37) ~[farmersdelight:1.16.3-0.2.4b] {re:classloading}
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:?] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3247/000000000000000000.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3741/000000000000000000.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

**Describe the issue**
For now I'll just switch to another JRE but looks like something is subtly off with the biome generation registration.

The code that is triggering this is:
```
		MinecraftForge.EVENT_BUS.addListener(EventPriority.HIGH, CropPatchGeneration::onBiomeLoad);
```
https://github.com/vectorwing/FarmersDelight/blob/1.16.3/src/main/java/vectorwing/farmersdelight/FarmersDelight.java#L37

Not 100% sure why. Though SimpleFarming has the same issue though out of the 240+ mods in Enigmatica 6 0.3.2

**Comment by telemenar** [comment]
Just learned that OpenJ9 is not a valid JVM for forge but newer versions of OpenJ9 are not caught. Closing as invalid.
