### ISSUE TITLE
Server crashing because of this mod

### ISSUE THREAD

**Issue by ghost** [vectorwing/FarmersDelight#387]
[17:02:59] [main/WARN] [mixin/]: Error loading class: vectorwing/farmersdelight/setup/Configuration (java.lang.ClassNotFoundException: Failed to find class bytes for vectorwing.farmersdelight.setup.Configuration)
Exception in thread "main" [17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at java.lang.reflect.Method.invoke(Method.java:498)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: ... 7 more
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at net.minecraft.util.registry.Registry.func_218353_F(Registry.java:159)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at net.minecraft.util.registry.Registry.lambda$static$51(Registry.java:466)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: at net.minecraft.server.Main.main(Main.java:92)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: ... 13 more
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: vectorwing.farmersdelight.setup.Configuration
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:771)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:741)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[17:02:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: ... 29 more

**Comment by vectorwing** [comment]
Please fill the bug report template with the requested information:
- Minecraft version
- Mod list (Forge and FD versions required)
- The full crash log (you can use websites like https://pastebin.com to upload them).

**Comment by ghost** [comment]
https://pastebin.com/mezBK9dh
1.16.5
![image](https://user-images.githubusercontent.com/45406683/149975390-c4d8606b-329d-47cd-a579-af3f528ddb93.png)
![image](https://user-images.githubusercontent.com/45406683/149975465-98c24e01-32e7-4ca0-8ccd-639c6285c1a5.png)
![image](https://user-images.githubusercontent.com/45406683/149975503-e4abe2bd-1151-49e3-8f49-7f5972dee615.png)
![image](https://user-images.githubusercontent.com/45406683/149975538-5b06f1eb-c608-49f4-9fbc-1850854ca351.png)
![image](https://user-images.githubusercontent.com/45406683/149975567-99a1a4e1-1661-4e76-a722-4a54fdccacb0.png)
![image](https://user-images.githubusercontent.com/45406683/149975599-5a3d7d72-f3dd-4dfa-938b-316770fe9e3e.png)
![image](https://user-images.githubusercontent.com/45406683/149975634-7f44881c-7aa1-4646-a4cb-250aa8b738a4.png)
![image](https://user-images.githubusercontent.com/45406683/149975710-08f907f4-3726-4610-9149-fb39d99e4d74.png)
![image](https://user-images.githubusercontent.com/45406683/149975752-916cc7a9-0dd9-4b41-947c-b411f3e12378.png)

**Comment by ghost** [comment]
forge 1.16.5 36.2.20

**Comment by vectorwing** [comment]
Hmm, not sure what's happening. At a glance, someone is trying to apply mixins to FD's Configuration.java and facing issues, but no hint as to where it came from.

You have a rather long mod list; please try doing a "binary search" to see if you can spot the culprit:

- Disable/remove half of your mods temporarily;
- Boot Minecraft and see if the issue persists:
  - If it does, disable/remove half of the remaining mods and try again;
  - If the issue stopped, see which mod might have caused it.

**Comment by vectorwing** [comment]
@pmalysYT Just following up on this issue. Is it still happening? Were you able to binary-search your mod list?

**Comment by vectorwing** [comment]
@pmalysYT I'm closing the issue for now, since it has gotten stale (30 days). If the issue is still going, feel free to reply to it anytime, and I'll reopen it. 👍
