### ISSUE TITLE
[1.18.1] Cooking Pot Causing Chunk Corruption and Crash

### ISSUE THREAD

**Issue by nthgava** [vectorwing/FarmersDelight#400]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Upon entering my world, I found a corrupted chunk in my cooking area

**Steps to reproduce:**
Not sure, place and use a cooking pot then leave and re-enter the world? Also crashes upon going to the nether and returning to the overworld.

**Expected behavior:**
Not sure

**Logs**
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/25/22, 1:01 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag vectorwing.farmersdelight.common.block.entity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.writeItems(CookingPotBlockEntity.java:110) ~[FarmersDelight-1.18.1-1.0.2a.jar%2370!/:1.18.1-1.0.2a] {re:classloading}
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.m_5995_(CookingPotBlockEntity.java:441) ~[FarmersDelight-1.18.1-1.0.2a.jar%2370!/:1.18.1-1.0.2a] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_140184_(ChunkMap.java:1009) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8385_(ServerChunkCache.java:448) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:850) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:tetra.mixins.json:MixinServerPlayNetHandler,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.m_5797_(ServerboundMovePlayerPacket.java:16) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1012996680 bytes (966 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x591b
	Graphics card #0 versionInfo: DriverVersion=22.20.16.4749
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1c8d
	Graphics card #1 versionInfo: DriverVersion=26.21.14.4587
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24911.89
	Virtual memory used (MB): 17277.44
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 276.72
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['WimpusMaximus'/802, l='ServerLevel[Singleplayer Delight]', x=-401.50, y=65.00, z=-799.81]]
	Data Packs: vanilla, mod:tetra (incompatible), mod:sereneseasons (incompatible), mod:mcwbridges, mod:farmersdelight, mod:zombieawareness (incompatible), mod:dustrial_decor (incompatible), mod:regrowth (incompatible), mod:immersiveengineering, mod:coroutil (incompatible), mod:globalxp, mod:paraglider (incompatible), mod:forge, mod:aquaculture (incompatible), mod:torohealth (incompatible), mod:flywheel, mod:mutil (incompatible), mod:create, mod:xaerominimap, mod:clumps (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:storagedrawers (incompatible), mod:modnametooltip (incompatible), mod:neat (incompatible), mod:jei (incompatible), mod:usefulbackpacks, mod:quarkoddities (incompatible), mod:curios, mod:curiosquarkobp, mod:travelersbackpack, mod:sophisticatedbackpacks (incompatible), mod:uteamcore, mod:libraryferret, mod:awesomedungeon, mod:waterstrainer, mod:dungeonsmod, mod:toolbelt (incompatible), mod:goblintraders (incompatible), mod:artifacts, mod:decorative_blocks, mod:expandability (incompatible), mod:darkpaintings, mod:mcwlights, mod:blue_skies (incompatible), mod:waystones, mod:balm (incompatible), mod:structure_gel, mod:voidtotem
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		DungeonsMod-1.18-1.4.60.jar                       |Dungeons Mod                  |dungeonsmod                   |1.18-1.4.60         |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.18.1-1.3.2.jar                       |Blue Skies                    |blue_skies                    |1.3.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.18.1-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.0-1.18.1.jar                    |Goblin Traders                |goblintraders                 |1.7.0               |DONE      |Manifest: NOSIGNATURE
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |DONE      |Manifest: NOSIGNATURE
		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |DONE      |Manifest: NOSIGNATURE
		Neat 1.8-30.jar                                   |Neat                          |neat                          |1.8-30              |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.3.jar                  |Waystones                     |waystones                     |9.0.3               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |DONE      |Manifest: NOSIGNATURE
		awesomedungeon-2.0.4.jar                          |Awesome Dungeon               |awesomedungeon                |2.0.4               |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.16.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.16.0              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.18.1-7.0.1.jar                |Traveler's Backpack           |travelersbackpack             |7.0.1               |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.1-4.0.2.jar                        |Artifacts                     |artifacts                     |1.18.1-4.0.2        |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.10-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.10     |DONE      |Manifest: NOSIGNATURE
		zombieawareness-1.18.1-1.12.3.jar                 |Zombie Awareness              |zombieawareness               |1.18.1-1.12.3       |DONE      |Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.18.1-2.0.4.jar          |Decorative Blocks             |decorative_blocks             |2.0.4               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.15.1.505.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.15.1.505   |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.18.1-4.0.0.201-SNAPSHOT.jar         |U Team Core                   |uteamcore                     |4.0.0.201-SNAPSHOT  |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |DONE      |Manifest: NOSIGNATURE
		WaterStrainer-1.18-12.1.0.jar                     |Water Strainer                |waterstrainer                 |1.18-12.1.0         |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.18-1.5.0.0.jar                       |Paraglider                    |paraglider                    |1.5.0.0             |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.59-universal.jar                |Forge                         |forge                         |39.0.59             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		structure_gel-1.18.1-2.1.2.jar                    |Structure Gel API             |structure_gel                 |2.1.2               |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.1-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.18.1-1.12.1.92-SNAPSHOT.jar    |Useful Backpacks              |usefulbackpacks               |1.12.1.92-SNAPSHOT  |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		DustrialDecor-1.3.1-1.18.jar                      |'Dustrial Decor               |dustrial_decor                |1.2.8               |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.18-1.18.0.jar                          |Tool Belt                     |toolbelt                      |1.18.0              |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.1-7.1.0-145.jar         |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.0      |DONE      |Manifest: NOSIGNATURE
		tetra-1.18.1-4.4.0.jar                            |Tetra                         |tetra                         |4.4.0               |DONE      |Manifest: NOSIGNATURE
		CuriosQuarkOBP-1.18.1-1.1.0.jar                   |Curios Quark Oddities Backpack|curiosquarkobp                |1.1.0               |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.1-4.2.0.jar                            |mutil                         |mutil                         |4.2.0               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.23.1_Forge_1.18.jar             |Xaero's Minimap               |xaerominimap                  |21.23.1             |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |DONE      |Manifest: NOSIGNATURE
		Regrowth--1.18.1-1.39.0.25.jar                    |Regrowth Mod                  |regrowth                      |1.18.1-1.39.0.25    |DONE      |Manifest: NOSIGNATURE
		coroutil-1.18.1-1.2.37.jar                        |CoroUtil                      |coroutil                      |1.18.1-1.2.37       |DONE      |Manifest: NOSIGNATURE
		globalxp-1.18.1-1.9.1.jar                         |Global XP                     |globalxp                      |1.9.1               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.1-2.3.2.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.2        |DONE      |Manifest: NOSIGNATURE
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |DONE      |Manifest: NOSIGNATURE
		voidtotem-forge-1.18.1-1.1.0.jar                  |Void Totem                    |voidtotem                     |1.18.1-1.1.0        |DONE      |Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.18.1-9.0.3.jar              |DarkPaintings                 |darkpaintings                 |9.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcw-lights-1.0.2-mc1.18.1.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 8768567a-0a30-4b8e-b98e-1f4ca324b1f3
	FML: 39.0
	Forge: net.minecraftforge:39.0.59
	Flywheel Backend: GL33 Instanced Arrays

**Screenshots**
None.

**Mod list:**
In the crash report, 51 mods in all

Note****

Was able to undo the corruption by replacing all cooking pots with air, then reloading the world. However, when will this issue be fixed?

**Comment by vectorwing** [comment]
This is really strange... 1.0.3 is supposed to have fixed this problem.
Do you still have a previous FD version on your mods folder? If not, can you try making a minimal instance with FD (and maybe JEI) to see if the issue persists?

**Comment by alexrsosa97** [comment]
i also have this problem, my world wont load

**Comment by vectorwing** [comment]
I think I figured out the problem. 🤔 

The only way for me to make 1.0.3 cause this crash on latest Forge was if an older .jar of FD was in the mods folder as well:

![image](https://user-images.githubusercontent.com/5566692/151086823-9bbb8256-4bc7-4e06-8ca5-ec31ae8212d8.png)

The latest Forge version currently has a version-selection problem, which makes it prefer the older version, while saying it's on the later version. It's an issue which doesn't appear in the crashlog, because the game thinks it's on the later version, and only prints that one.

**Please make sure you only have 1 single .jar of FD on your mods folder, and that it's the 1.0.3 version.** It's very important to delete the older versions when updating any mods.

If this isn't your case, please reopen and let me know.
