### ISSUE TITLE
[1.18.1] Version 1.0.2a crash

### ISSUE THREAD

**Issue by mont-40** [vectorwing/FarmersDelight#403]
**Description**
Crash

**Steps to reproduce:**
Just play the game.

**Expected behavior:**
No crash.

**Logs**
```
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag vectorwing.farmersdelight.common.block.entity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.writeItems(CookingPotBlockEntity.java:110) ~[FarmersDelight-1.18.1-1.0.2a.jar%2359!/:1.18.1-1.0.2a] {re:classloading}
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.m_5995_(CookingPotBlockEntity.java:441) ~[FarmersDelight-1.18.1-1.0.2a.jar%2359!/:1.18.1-1.0.2a] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1459) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:1009) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.level.ChunkMap.m_140184_(ChunkMap.java:1279) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.level.ServerChunkCache.m_8385_(ServerChunkCache.java:448) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:850) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tetra.mixins.json:MixinServerPlayNetHandler,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.m_5797_(ServerboundMovePlayerPacket.java:16) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$checkThreadAndEnqueue$0(PacketUtils.java:38) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[OptiFine_1.18.1_HD_U_H4.jar%2383!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:193) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:158) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:171) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

**Mod list:**
```
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tetra-1.18.1-4.4.0.jar                            |Tetra                         |tetra                         |4.4.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.2a.jar                  |Farmer's Delight              |farmersdelight                |1.18.1-1.0.2a       |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.4.1_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		horsestatsmod-MC1.18.x-1.4.3.jar                  |Horse Stats Mod               |horsestatsmod                 |1.4.3               |DONE      |Manifest: NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.7.2               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.1-1.0.4.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		Neat+1.8-30.jar                                   |Neat                          |neat                          |1.8-30              |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.1-4.2.0.jar                            |mutil                         |mutil                         |4.2.0               |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.18.1-6.0.0.jar                    |Fast Workbench                |fastbench                     |6.0.0               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.1-6.0.3.jar                          |Placebo                       |placebo                       |6.0.3               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.10-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.10     |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.18.1.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.18.1-6.0.1.jar                      |FastFurnace                   |fastfurnace                   |6.0.1               |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |4.0.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		SnowRealMagic-1.18-forge-3.1.0.jar                |Snow! Real Magic!             |snowrealmagic                 |3.1.0               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.18-forge-5.2.3.jar                         |Kiwi                          |kiwi                          |5.2.3               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.59-universal.jar                |Forge                         |forge                         |39.0.59             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
		extremesoundmuffler-3.22_forge-1.18.1.jar         |Extreme Sound Muffler         |extremesoundmuffler           |3.22_forge-1.18.1   |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.0.12_Fabric+Forge.jar                |Seed Fix + Terralith          |seedfix_forge                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
```

**Comment by vectorwing** [comment]
You're currently playing an outdated version. Please update FD to 1.0.3 if you're on Forge 39.0.45 or above.
