### ISSUE TITLE
[1.18.1] Server Hangs indefinitely after breaking stove with items on it

### ISSUE THREAD

**Issue by Synthestra** [vectorwing/FarmersDelight#409]
**Description**
After placing items onto a stove (in my case, 6 potatoes) and breaking the stove, the items will not be able to be picked up, indicating that the server has frozen. interacting with blocks, attempting to send chat messages, etc, will fail. attempting to close the world (singleplayer) will show the "Saving World" message indefinitely until force-closed. 

**Steps to reproduce:**
Place stove, place 6 Potatoes on stove, break stove

**Expected behavior:**
Server won't crash

**Logs**
[04:11:04] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.rehash(Long2ObjectOpenHashMap.java:1335) ~[fastutil-8.5.6.jar%2343!/:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.insert(Long2ObjectOpenHashMap.java:279) ~[fastutil-8.5.6.jar%2343!/:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.put(Long2ObjectOpenHashMap.java:287) ~[fastutil-8.5.6.jar%2343!/:?]
	at net.minecraft.world.level.levelgen.structure.StructureCheck.m_197263_(StructureCheck.java:226) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.world.level.levelgen.structure.StructureCheck.m_197282_(StructureCheck.java:222) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.level.ServerLevel.lambda$onStructureStartsAvailable$25(ServerLevel.java:1505) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:193) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:158) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23133!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Mod list:**
https://pastebin.com/tiVWzT36

**Comment by vectorwing** [comment]
This sounds like a potentially strange interaction with FastUtils. If I'm not mistaken, it's part of Placebo, FastFurnace and FastWorkbench.

A few questions:
- Is the server world currently unbootable due to this problem, or did it reload normally?
- Did the server suffer previously from the pre-1.0.3 Forge bug, where placing a pot would corrupt the chunk?

My suggestion is to try and boot the server with the FastUtils mods disabled temporarily, and see if the problem persists.

**Comment by vectorwing** [comment]
@Synthestra, just following up on this issue. Are you still facing his problem, or tried the suggestions above?

**Comment by vectorwing** [comment]
Issues seems to be resolved with general mod updates, after following up with Synthestra on Discord. 👍
