### ISSUE TITLE
[1.18.1] Conflict with Helpful Faeries Mod

### ISSUE THREAD

**Issue by atspulgs** [vectorwing/FarmersDelight#414]
**Description**
The game crashed after I spawned a Faerie from the following mod: ([Helpful Faeries](https://www.curseforge.com/minecraft/mc-mods/helpful-faeries))
This could be a bug with Faeries mod too, but I did not see a convenient way to report it to the author. (I left a comment on their page linking to this, my hope is that the two mods could play nice with each other as I feel like they complement each other)

**Forge**
Forge: net.minecraftforge:39.0.63

**Steps to reproduce:**
I assume, to have crops planted, specifically tomatoes. (I think)
Manage to summon faerie using the survival intended method.
Faries Lantern needs to exist nearby too.

**Expected behaviour:**
For the game not to crash.
I would love to see the two mods working together.

**Logs**
```
I am adding the exceptions only here, I will add the list of mods I am running during this time as well later in the post.
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 06/02/2022, 11:38
Description: Ticking entity

java.lang.ClassCastException: class vectorwing.farmersdelight.common.block.TomatoBlock cannot be cast to class net.minecraft.world.level.block.CropBlock (vectorwing.farmersdelight.common.block.TomatoBlock is in module farmersdelight@1.18.1-1.0.3 of loader 'TRANSFORMER' @2582b0ef; net.minecraft.world.level.block.CropBlock is in module minecraft@1.18.1 of loader 'TRANSFORMER' @2582b0ef)
	at com.forestofthegods.helpfulfaeries.entity.ai.FaeAILocateCrops.m_6465_(FaeAILocateCrops.java:127) ~[helpfulfaeries-1.0.jar%2380!/:1.0] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_25626_(MoveToBlockGoal.java:119) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_8036_(MoveToBlockGoal.java:47) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at com.forestofthegods.helpfulfaeries.entity.ai.FaeAILocateCrops.m_8036_(FaeAILocateCrops.java:41) ~[helpfulfaeries-1.0.jar%2380!/:1.0] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8036_(WrappedGoal.java:22) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:98) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:920) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2501) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:620) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at com.forestofthegods.helpfulfaeries.entity.FaerieEntity.m_8107_(FaerieEntity.java:210) ~[helpfulfaeries-1.0.jar%2380!/:1.0] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:381) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.forestofthegods.helpfulfaeries.entity.ai.FaeAILocateCrops.m_6465_(FaeAILocateCrops.java:127) ~[helpfulfaeries-1.0.jar%2380!/:1.0] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_25626_(MoveToBlockGoal.java:119) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_8036_(MoveToBlockGoal.java:47) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at com.forestofthegods.helpfulfaeries.entity.ai.FaeAILocateCrops.m_8036_(FaeAILocateCrops.java:41) ~[helpfulfaeries-1.0.jar%2380!/:1.0] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8036_(WrappedGoal.java:22) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:98) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:920) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2501) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:620) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at com.forestofthegods.helpfulfaeries.entity.FaerieEntity.m_8107_(FaerieEntity.java:210) ~[helpfulfaeries-1.0.jar%2380!/:1.0] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:381) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: helpfulfaeries:faerie (com.forestofthegods.helpfulfaeries.entity.FaerieEntity)
	Entity ID: 90539
	Entity Name: entity.helpfulfaeries.faerie
	Entity's Exact location: -227.99, 79.99, -476.99
	Entity's Block location: World: (-228,79,-477), Section: (at 12,15,3 in -15,4,-30; chunk contains blocks -240,-64,-480 to -225,319,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.01, -0.01, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23105!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

**Screenshots**
N/A (game crashed so nothing to screenshot)

**Mod list:**
```
Mod List: 
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		DisenchantmentEditTable-1.18-1.0.5.jar            |Enchantment Edit Table        |editenchanting                |1.0.5               |DONE      |Manifest: NOSIGNATURE
		ConfigMenusForge-v3.1.0-1.18.1-Forge.jar          |Config Menus for Forge        |configmenusforge              |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.1-9.1.1.48.jar                           |Just Enough Items             |jei                           |9.1.1.48            |DONE      |Manifest: NOSIGNATURE
		Netherited-forge-1.18-1.2.0.jar                   |Netherited                    |netherited                    |1.2.0               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18-3.0.0.1.jar                     |Caelus API                    |caelus                        |1.18-3.0.0.1        |DONE      |Manifest: NOSIGNATURE
		NyfsQuiver-1.18.1-0.6.4.jar                       |Nyf's Quiver                  |nyfsquiver                    |1.18.1-0.6.3        |DONE      |Manifest: NOSIGNATURE
		nyfsquiversexpanded-1.18.1-0.1.0.jar              |Nyfs Quivers Expanded         |nyfsquiversexpanded           |0.1.0               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta11.jar                 |Journeymap                    |journeymap                    |5.8.0beta11         |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0+13.jar               |Controlling                   |controlling                   |9.0+13              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.1-6.0.5.jar                          |Placebo                       |placebo                       |6.0.5               |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		FruitTrees-1.18-forge-4.1.2.jar                   |Fruit Trees                   |fruittrees                    |4.1.2               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.18-forge-5.2.3.jar                         |Kiwi                          |kiwi                          |5.2.3               |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.1-4.0.2.jar                        |Artifacts                     |artifacts                     |1.18.1-4.0.2        |DONE      |Manifest: NOSIGNATURE
		ItemBorders-1.18.1-1.1.5.jar                      |Item Borders                  |itemborders                   |1.1.5               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.14.3.485.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.14.3.485   |DONE      |Manifest: NOSIGNATURE
		ore_tree-0.2.3.jar                                |Ore Tree                      |ore_tree                      |0.2.3               |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.18.1-2.2.3-beta.1.jar              |Guide-API VP                  |guideapi_vp                   |2.2.3-beta.1        |DONE      |Manifest: NOSIGNATURE
		Apotheosis-1.18.1-5.2.2.jar                       |Apotheosis                    |apotheosis                    |5.2.2               |DONE      |Manifest: NOSIGNATURE
		PickUpNotifier-v3.1.0-1.18.1-Forge.jar            |Pick Up Notifier              |pickupnotifier                |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		catalogue-1.6.0-1.18.1.jar                        |Catalogue                     |catalogue                     |1.6.0               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.138.jar         |Just Enough Resources         |jeresources                   |0.13.1.138          |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		LavaClearView-1.18-forge-3.0.1.jar                |Lava Clear View               |clearview                     |3.0.1               |DONE      |Manifest: NOSIGNATURE
		EquipmentCompare-1.18.1-1.2.10.jar                |Equipment Compare             |equipmentcompare              |1.2.10              |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.18.1-1.4.2.jar               |Advancement Plaques           |advancementplaques            |1.4.2               |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		Jade-1.18-4.1.2.jar                               |Jade                          |jade                          |4.1.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.63-universal.jar                |Forge                         |forge                         |39.0.63             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		helpfulfaeries-1.0.jar                            |Helpful Faeries               |helpfulfaeries                |1.0                 |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16a-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16a             |DONE      |Manifest: NOSIGNATURE
		Highlighter-1.18.1-1.1.2.jar                      |Highlighter                   |highlighter                   |1.1.2               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.1-1.0.39.jar                         |Iceberg                       |iceberg                       |1.0.39              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.4.1.jar                   |Curios API                    |curios                        |1.18.1-5.0.4.1      |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.18.1-1.2.0.jar                |Legendary Tooltips            |legendarytooltips             |1.2.0}              |DONE      |Manifest: NOSIGNATURE
		itemcollectors-1.1.4-mc1.18.jar                   |Item Collectors               |itemcollectors                |1.1.4               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.1-1.0.0.jar                       |Gravestone Mod                |gravestone                    |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		advancednetherite-1.10.0-1.18.1.jar               |Advanced Netherite            |advancednetherite             |1.10.0              |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18-1.2.2.jar              |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.18].forge-3.4.4.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre28-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre28         |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.3.0.jar                  |AppleSkin                     |appleskin                     |2.3.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		curiouselytra-forge-1.18.1-5.0.1.0.jar            |Curious Elytra                |curiouselytra                 |1.18.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE
		globalxp-1.18.1-1.9.1.jar                         |Global XP                     |globalxp                      |1.9.1               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.1.3-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.1.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterF3-1.2.2-Forge-1.18.jar                     |BetterF3                      |betterf3                      |1.2.2               |DONE      |Manifest: NOSIGNATURE
		ears-forge-1.18-1.4.5.jar                         |Ears                          |ears                          |1.4.5               |DONE      |Manifest: NOSIGNATURE
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |DONE      |Manifest: NOSIGNATURE
		convenientcurioscontainer-1.1-1.18.jar            |Convenient Curios Container   |convenientcurioscontainer     |1_forge-1.18        |DONE      |Manifest: NOSIGNATURE
		UniversalClockHUD-FORGE-1.18.1-v1.4.0.jar         |Universal Clock HUD           |universalclockhud             |1.18.1-v1.4.0       |DONE      |Manifest: NOSIGNATURE
```

**Comment by atspulgs** [comment]
I updated Forgemod to 39.0.66 and the faeries mod failed to load altogether. Clearly, its author has to do some work... so you won't be able to recreate the issues with that particular version either.

**Comment by RaymondBlaze** [comment]
From my point of view, the problem is actually on the Helpful Faeries Mod's side: The crash is caused by some code in the Faery's AI trying to cast TomatoBlock into CropBlock. However, TomatoBlock, though seems like a crop on the player's point of view, is actually not a subclass of CropBlock. So the class cast is illegal and crashes the game, providing the java.lang.ClassCastException as you see in the log.
As the problem is actually on Helpful Faeries' side, I think there is no way to fix this except contacting its author and wait for him/her to provide a possible fix/solution. Sadly, I didn't manage to find the Helpful Faeries repo link either on CurseForge or in the mods.toml, though its marked as using MIT license (weird). So maybe all you can do is wait and hope for the author sees your issue in the comments?
P.S. Even when the problem is fixed, it's more likely going to be like "only blocks who extend CropBlock will be harvested" than your dreamed automatic faery-based tomato farm, as there is no way to tell if a crop-like block who doesn't extends CropBlock is at it's max age unless an active integration is provided.

**Comment by atspulgs** [comment]
Crushing my dreams here of a majestic Tomato farm here :D I am heartbroken!!!

Thank you for looking into this. It would seem like this is fully onto the Faeries mod authors shoulders to properly handle their checks.
I wont keep this open as there is nothing for you to do.
