### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by Mayzone** [vectorwing/FarmersDelight#557]
**Description**
Starting server, creates this error. Server doesn't crash.

**Steps to reproduce:**
Starting magma server

**Expected behavior:**
Starting server without error

**Logs**
`[15:28:04] [Worker-Main-9/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe farmersdelight:integration/botanypots/crops/tomatoes
com.google.gson.JsonParseException: Expected member drops was not found.
        at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSONList(ISerializer.java:234) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:24) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:14) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.bookshelf.impl.data.recipes.WrappedRecipeSerializer.m_6729_(WrappedRecipeSerializer.java:23) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.1.80-universal.jar%23137!/:?] {re:classloading}
        at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:179) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:71) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,re:computing_frames,re:classloading}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[15:28:04] [Worker-Main-9/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe farmersdelight:integration/botanypots/crops/cabbages
com.google.gson.JsonParseException: Expected member drops was not found.
        at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSONList(ISerializer.java:234) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:24) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:14) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.bookshelf.impl.data.recipes.WrappedRecipeSerializer.m_6729_(WrappedRecipeSerializer.java:23) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.1.80-universal.jar%23137!/:?] {re:classloading}
        at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:179) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:71) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,re:computing_frames,re:classloading}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[15:28:04] [Worker-Main-9/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe farmersdelight:integration/botanypots/crops/onions
com.google.gson.JsonParseException: Expected member drops was not found.
        at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSONList(ISerializer.java:234) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:24) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:14) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.bookshelf.impl.data.recipes.WrappedRecipeSerializer.m_6729_(WrappedRecipeSerializer.java:23) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.1.80-universal.jar%23137!/:?] {re:classloading}
        at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:179) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:71) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,re:computing_frames,re:classloading}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[15:28:05] [Worker-Main-9/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe farmersdelight:integration/botanypots/crops/rice_crop
com.google.gson.JsonParseException: Expected member drops was not found.
        at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSONList(ISerializer.java:234) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:24) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:14) ~[Botany-Pots-Mod-Forge-1.18.2.jar%2363!/:8.0.12] {re:classloading}
        at net.darkhax.bookshelf.impl.data.recipes.WrappedRecipeSerializer.m_6729_(WrappedRecipeSerializer.java:23) ~[Bookshelf-API-Library-Forge-1.18.2.jar%2362!/:13.2.50] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.1.80-universal.jar%23137!/:?] {re:classloading}
        at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:179) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:71) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:mixin,re:computing_frames,re:classloading}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23132!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}`

**Mod list:**
FarmersDelight-1.18.2-1.1.2.jar
Magma-1.18.2-40.1.80-89c70113-server.jar

**Comment by vectorwing** [comment]
This was due to outdated schemas in my Botany Pots integration. Darkhax fixed it by submitting PR #552, which should be out in the next patch. 👍
