### ISSUE TITLE
Latest update results in a crash [Fabric 1.19.2]

### ISSUE THREAD

**Issue by gamerpotion** [vectorwing/FarmersDelight#590]
Hi, we are using this in our modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

version _farmers-delight-fabric-1.19.X-1.3.5.jar_ worked perfectly fine till now. 
After updating to version _farmers-delight-fabric-1.19.X-1.3.6.jar_ , it results in the following crash on startup.

```02:01:31.297
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at com.nhoryzon.mc.farmersdelight.registry.ItemsRegistry.<clinit>(ItemsRegistry.java:140)
	at net.minecraft.class_1799.<clinit>(class_1799.java:126)
	at net.minecraft.class_1761.<init>(class_1761.java:114)
	at net.minecraft.class_1761$1.<init>(class_1761.java:15)
	at net.minecraft.class_1761.<clinit>(class_1761.java:15)
	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder.build(FabricItemGroupBuilder.java:167)
	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder.build(FabricItemGroupBuilder.java:158)
	at com.kwpugh.gobber2.Gobber2.<clinit>(Gobber2.java:21)
	at net.minecraft.class_5134.modify$ego000$gobberModifyMax(class_5134.java:525)
	at net.minecraft.class_5134.<clinit>(class_5134.java:14)
	at net.minecraft.class_1294.<clinit>(class_1294.java:15)
	at net.minecraft.class_2246.<clinit>(class_2246.java:237)
	at net.minecraft.class_5872.<clinit>(class_5872.java:9)
	at net.minecraft.class_5871.method_33968(class_5871.java:20)
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at net.minecraft.class_5871.<clinit>(class_5871.java:16)
	at net.minecraft.class_2939.<clinit>(class_2939.java:32)
	at net.minecraft.class_5463.<clinit>(class_5463.java:21)
	at net.minecraft.class_5458.method_30572(class_5458.java:66)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1291.method_42127()" because "$$0" is null
	at net.minecraft.class_1293.<init>(class_1293.java:51)
	at net.minecraft.class_1293.<init>(class_1293.java:47)
	at net.minecraft.class_1293.<init>(class_1293.java:43)
	at com.nhoryzon.mc.farmersdelight.item.enumeration.Foods.<clinit>(Foods.java:17)
	... 30 more
02:01:31.537
launcher
main

02:01:31.537
monitor
Process Monitor
Process crashed with exit code 1

**Comment by vectorwing** [comment]
Sorry, this issues board is only for the Forge version. Please use the form next time. :(
You can report Fabric issues here: https://github.com/newhoryzon/farmers-delight-fabric/issues
