### ISSUE TITLE
[MC Version]: 1.16.4

### ISSUE THREAD

**Issue by rdyEmber** [vectorwing/FarmersDelight#610]
### Description

i was testing a new modpack that i was making for my friends to play together and we installed a lot of mods, even farmers delight
sadly for me when i tried to join a server i made on aternos i was greated with crash
mc version 1.16.5*

### Steps to reproduce

1. download all mods listed in image: https://i.imgur.com/FdBzJrg.png
2. create aternos server with the same mods
3. join a server

### Mod list

[https://i.imgur.com/FdBzJrg.png](url)

### Logs

---- Minecraft Crash Report ----
// You're mean.

Time: 25.12.22 22:23
Description: Unexpected error

java.lang.NullPointerException: Registry Object not present: farmersdelight:comfort
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:106) ~[?:?] {re:mixin,re:classloading}
	at vectorwing.farmersdelight.client.gui.ComfortHealthOverlay.onRender(ComfortHealthOverlay.java:69) ~[?:1.16.5-0.6.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_813_ComfortHealthOverlay_onRender_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3019/1784533123.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:818) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:etched.mixins.json:client.ForgeIngameGuiMixin,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHealth(ForgeIngameGui.java:484) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:etched.mixins.json:client.ForgeIngameGuiMixin,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:149) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:etched.mixins.json:client.ForgeIngameGuiMixin,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:magnesium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/889885902.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:106) ~[?:?] {re:mixin,re:classloading}
	at vectorwing.farmersdelight.client.gui.ComfortHealthOverlay.onRender(ComfortHealthOverlay.java:69) ~[?:1.16.5-0.6.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_813_ComfortHealthOverlay_onRender_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3019/1784533123.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:818) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:etched.mixins.json:client.ForgeIngameGuiMixin,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHealth(ForgeIngameGui.java:484) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:etched.mixins.json:client.ForgeIngameGuiMixin,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:149) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:etched.mixins.json:client.ForgeIngameGuiMixin,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinIngameGui,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['rdyEmber'/170, l='ClientLevel', x=130.50, y=65.00, z=239.50]]
	Chunk stats: Client Chunk Cache: 1024, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,65,240), Chunk: (at 0,4,0 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1279 game time, 1279 day time
	Server brand: forge arclight
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:458) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pollen-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:magnesium.mixins.json:features.world_ticking.MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/889885902.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 551751808 bytes (526 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |Manifest: NOSIGNATURE
		Hats-1.16.5-10.3.3.jar                            |Hats                          |hats                          |10.3.3              |DONE      |Manifest: NOSIGNATURE
		FencesAndWalls-v1.0.7-mc1.16.5-Forge.jar          |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		does_it_tick-1.16.5_v2.0.0.jar                    |Template Mod                  |does_it_tick                  |1.16.5_v2.0.0       |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		MacawWindows-v2.0.3-mc1.16.5-Forge.jar            |Macaw's Windows               |mcwwindows                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		Forge-1.16.5-Etched-2.2.0.jar                     |Etched                        |etched                        |2.2.0               |DONE      |Manifest: NOSIGNATURE
		Forge-1.16.5-Pollen-1.5.0.jar                     |Pollen                        |pollen                        |1.5.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.99m.jar                     |Performant                    |performant                    |3.73m               |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.8-1.16.5.jar                       |Backpacked                    |backpacked                    |2.1.8               |DONE      |Manifest: NOSIGNATURE
		simplytea-1.16.5-2.4.0.jar                        |Simply Tea                    |simplytea                     |2.4.0               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.8.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.8               |DONE      |Manifest: NOSIGNATURE
		SWIceandFire-1.16.5-1.0.1.jar                     |Spartan Weaponry: Ice and Fire|swiaf                         |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		magnesium-1.5.jar                                 |Magnesium                     |magnesium                     |1.5                 |DONE      |Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.5-2.2.0-rc-2.jar             |Spartan Weaponry              |spartanweaponry               |2.2.0 Release Candid|DONE      |Manifest: NOSIGNATURE
		ArchitecturyAPI-Forge-1.16.5-v1.32.66.jar         |Architectury                  |architectury                  |1.32.66             |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.9.0.jar                        |Vampirism                     |vampirism                     |1.9.0               |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		iceandfire-2.1.11-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.11-1.16.5       |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.16.91-1.16-forge.jar               |Cloth Config v4 API           |cloth-config                  |4.16.91             |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.6.1.jar                       |iChunUtil                     |ichunutil                     |10.6.1              |DONE      |Manifest: NOSIGNATURE
		magnesium_extras-mc1.16.5_v1.4.0.jar              |Magnesium Extras              |magnesium_extras              |mc1.16.5_v1.4.0     |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-322-1.16.5.jar                         |Quark                         |quark                         |r2.4-322            |DONE      |Manifest: NOSIGNATURE
		toms_storage-1.16.5-1.2.19.jar                    |Tom's Simple Storage Mod      |toms_storage                  |1.2.19              |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.25.9.jar                     |Ars Nouveau                   |ars_nouveau                   |1.25.9              |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-6.2.3-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.2.3-forge-mc1.16.5|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a81e1a9a-be98-42f5-84b5-d0311f56b21b
	Patchouli open book context: n/a
	Launched Version: 1.16.5-forge-36.2.39
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce 8400 GS/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible)
	Current Language: Русский (Россия)
	CPU: 2x AMD Athlon(tm) 64 X2 Dual Core Processor 4200+

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [x] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Sorry for the long delay, @rdyEmber!

Though I'm not updating for 1.16.5 anymore, I tried taking a look at this issue anyway, but could not replicate it. The only thing which could cause this problem is a version mismatch somehow.

On version 0.6, there were a few package changes which moved many classes around. However, this update was only for 1.16.5. If your server is using a 1.16.4 version of FD, then it will conflict with the 1.16.5 releases, which would cause it to not find `farmersdelight:comfort`. Please check if your *server* is properly updated to 1.16.5, given your issue title; I can see your client is on 0.6.

I'll be closing this issue for now, since there were no other reports of this bug afterwards. If the stuff above doesn't apply and the issue persists, feel free to reply here. 👍
