### ISSUE TITLE
[1.18.2]: Client side crash when join Velocity Server

### ISSUE THREAD

**Issue by DaanSchar** [vectorwing/FarmersDelight#640]
### Description

When joining the a [Velocity](https://velocitypowered.com/) powered server, the client throws the following error: `Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOfBoundsException: 14, length: 105 (expected: range(0, 54)).

This is with version `1.2.0`

> **__Note:__** joining with version `1.1.2` fixes the issue.

### Steps to reproduce

1. Load forge client with farmer's delight installed
2. Join Velocity Server.
3. crash and burn

### Mod list

* Minecraft
* Forge
* Farmer's Delight

### Logs

```
Error executing task on Client
java.util.NoSuchElementException: packet_handler
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at TRANSFORMER/forge@40.2.0/net.minecraftforge.network.filters.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:34)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196)
	at TRANSFORMER/forge@40.2.0/net.minecraftforge.network.filters.NetworkFilters.injectIfNecessary(NetworkFilters.java:30)
	at TRANSFORMER/forge@40.2.0/net.minecraftforge.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:108)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:375)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:83)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:19)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Hello! Sorry for the late reply, @DaanSchar.

I'm gonna need the full logs to see better what's going on. Please send me both your client and server logs.

**Comment by DaanSchar** [comment]
This was quite a while ago. Downgrading Farmer's Delight version fixed this!
