### ISSUE TITLE
[1.18.2]: TomatoBlock crashing the game

### ISSUE THREAD

**Issue by raphaela-loss-barreto** [vectorwing/FarmersDelight#666]
### Description

The TomatoBlock is crashing the game
When I drop tomatoes the game crashes

### Steps to reproduce

1. Go to a village
2. Drop tomatoes

### Mod list

- Tinkers' Construct 3.6.3.111
- Farmer's Delight 1.18.2-1.2.0
- TerraBlender 1.2.0.126
- Open Parties and Claims 0.17.0
- Biomes O' Plenty 16.0.0.134
- Just Enough Items 10.2.1.1004
- Botania 1.18.2-435
- Domum Ornamentum 1.18.2-1.0.77-ALPHA
- Library ferret 4.0.0
- Hefty Crops 1.18.2-1.1
- Immersive Weathering 1.18.2-1.18.2-3.0.3
- Curios API 1.18.2-5.0.9.0
- Patchouli 1.18.2-71.1
- Mantle 1.9.43
- UI Library Mod 1.18.2-0.0.71-ALPHA
- Xaero's Minimap 23.3.1
- Waystones 10.2.0
- Gravestone Mod 1.18.2-1.0.2
- Xaero's World Map 1.29.2
- Citadel 1.11.3
- Alex's Mobs 1.18.6
- Traveler's Backpack 7.1.26
- Smarter Farmers 1.18.2-1.6.0
- Better village 2.1.0
- Overweight Farming 1.18.2-1.6.0-forge
- Dungeon Crawl 2.3.12
- Structurize 1.18.2-1.0.424-ALPHA
- Multi-Piston 1.18.2-1.2.15-ALPHA
- Guard Villagers 1.4.3
- MineColonies 1.18.2-1.0.1285-ALPHA
- MrCrayfish's Furniture Mod 7.0.0-pre35
- Macaw's Furniture 3.1.0
- Balm 3.2.6
- FallingTree 3.5.4
- Forge 40.2.1
- The Twilight Forest 4.1.1494
- TLSkinCape 1.25
- GeckoLib 3.0.57
- Selene 1.18.2-1.17.9
- Supplementaries 1.18.2-1.5.16
- When Dungeons Arise 2.1.52-1.18.2

### Logs

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 19/03/2023 19:39
Description: Exception ticking world

java.lang.NoClassDefFoundError: vectorwing/farmersdelight/common/block/TomatoBlock
	at crispytwig.heftycrops.HeftyCrops.onCropGrow(HeftyCrops.java:89) ~[heftycrops-1.18.2-1.1.jar%2370!/:1.18.2-1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_11_HeftyCrops_onCropGrow_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPost(ForgeHooks.java:1063) ~[forge-1.18.2-40.2.1-universal.jar%2398!/:?] {re:classloading}
	at vectorwing.farmersdelight.common.block.TomatoVineBlock.m_7455_(TomatoVineBlock.java:85) ~[FarmersDelight-1.18.2-1.2.0.jar%2366!/:1.18.2-1.2.0] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60735_(BlockBehaviour.java:681) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:440) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:359) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:309) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.TomatoBlock
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at crispytwig.heftycrops.HeftyCrops.onCropGrow(HeftyCrops.java:89) ~[heftycrops-1.18.2-1.1.jar%2370!/:1.18.2-1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_11_HeftyCrops_onCropGrow_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPost(ForgeHooks.java:1063) ~[forge-1.18.2-40.2.1-universal.jar%2398!/:?] {re:classloading}
	at vectorwing.farmersdelight.common.block.TomatoVineBlock.m_7455_(TomatoVineBlock.java:85) ~[FarmersDelight-1.18.2-1.2.0.jar%2366!/:1.18.2-1.2.0] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60735_(BlockBehaviour.java:681) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:440) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:359) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:309) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['A'/62, l='ServerLevel[Novo mundo]', x=703.77, y=64.00, z=-1900.39]]
	Chunk stats: 5018
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 31123 game time, 15861 day time
	Level name: Novo mundo
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 89449 (now: false), thunder time: 127878 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:classloading,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

```

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by raphaela-loss-barreto** [comment]
The problem was Hefty Crops.
