### ISSUE TITLE
Issue with creative tab loading the game

### ISSUE THREAD

**Issue by bethjpeg** [vectorwing/FarmersDelight#722]
I have been trying to get farmer's delight (1.19-1.2.1) to work when i load my game but each time i load it gives me this error which i'll paste below. My friend has the same instance of farmer's delight but has no issue, and when i try removing each mod to see if any of them are clashing i still get the error.  Does anyone know what this could be an issue with? Thanks :)

Full crash report:
---- Minecraft Crash Report ----
// My bad.

Time: 2023-05-27 03:38:05
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.0.64-universal.jar%23177!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.0.64-universal.jar%23177!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:577) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:420) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:571) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:135) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:940) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jade.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1148) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:719) ~[client-1.19.4-20230314.122934-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-45.0.64.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.64.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at vectorwing.farmersdelight.FarmersDelight$1.<init>(FarmersDelight.java:35) ~[FarmersDelight-1.19-1.2.1.jar%23164!/:1.19-1.2.1] {re:classloading}
-- MOD farmersdelight --
Details:
	Failure message: Farmer's Delight (farmersdelight) has failed to load correctly
		java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
	Mod Version: 1.19-1.2.1
	Mod Issue URL: https://github.com/vectorwing/FarmersDelight/issues
	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'
Stacktrace:
	at vectorwing.farmersdelight.FarmersDelight$1.<init>(FarmersDelight.java:35) ~[FarmersDelight-1.19-1.2.1.jar%23164!/:1.19-1.2.1] {re:classloading}
	at vectorwing.farmersdelight.FarmersDelight.<clinit>(FarmersDelight.java:34) ~[FarmersDelight-1.19-1.2.1.jar%23164!/:1.19-1.2.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.64.jar%23174!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.64.jar%23173!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SereneSeasons-1.19.4-8.3.0.39.jar                 |Serene Seasons                |sereneseasons                 |8.3.0.39            |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.1.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.1          |ERROR     |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.4-2.2.0.156.jar           |TerraBlender                  |terrablender                  |2.2.0.156           |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.4-45.0.64-universal.jar                |Forge                         |forge                         |45.0.64             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		open-parties-and-claims-forge-1.19.4-0.17.3.jar   |Open Parties and Claims       |openpartiesandclaims          |0.17.3              |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.4-17.3.0.545.jar               |Biomes O' Plenty              |biomesoplenty                 |17.3.0.545          |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.4-5.1.5.1.jar                   |Curios API                    |curios                        |1.19.4-5.1.5.1      |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.4-forge-10.3.0.jar                      |Jade                          |jade                          |10.3.0              |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.4.3_Forge_1.19.4.jar            |Xaero's Minimap               |xaerominimap                  |23.4.3              |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19.4-4.1.3.jar                   |GeckoLib 4                    |geckolib                      |4.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		aether-1.19.4-1.0.0-beta.3-forge.jar              |The Aether                    |aether                        |1.19.4-1.0.0-beta.3-|COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.4-forge-13.1.0.11.jar                    |Just Enough Items             |jei                           |13.1.0.11           |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 80eec76d-7276-4f09-80f3-1075636ab850
	FML: 45.0
	Forge: net.minecraftforge:45.0.64

**Comment by vectorwing** [comment]
You're trying to run FD on Minecraft 1.19.4. The mod hasn't been ported to that version yet.

We will wait for 1.20 to release before porting. Sorry! ^^

**Comment by bethjpeg** [comment]
ahh i see, thank you! :)
