### ISSUE TITLE
Games crashes when i open a generated chest

### ISSUE THREAD

**Issue by SkylosQC** [vectorwing/FarmersDelight#841]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2

### Forge version

47.2.0

### Description

I'm playing on a minecraft server with my friends, i'm the host (using Bloom.host if this can be any useful) Everytime i open a generated chest, the game crashes, from any type of generated ones 

Help would be appreciated! I would like it if I could open those chests 

### Steps to reproduce

1. open chest
2. game (server) crashes

### Mod list

waystones
Simple voicechat
sereneSeasons
jei
FarmersDelight
Corpse
cfm forge
callable horses
balm forge

### Logs

---- Minecraft Crash Report ----
2
// Uh... Did I do that?
3
​
4
Time: 2023-11-17 00:57:33
5
Description: Exception in server tick loop
6
​
7
java.lang.StackOverflowError: Exception in server tick loop
8
    at java.util.HashMap.<init>(HashMap.java:484) ~[?:?] {}
9
    at com.google.common.collect.Maps.newHashMap(Maps.java:258) ~[guava-31.1-jre.jar%2374!/:?] {}
10
    at net.minecraft.nbt.CompoundTag.m_6426_(CompoundTag.java:439) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:mixin,re:classloading}
11
    at net.minecraft.nbt.CompoundTag.m_6426_(CompoundTag.java:21) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:mixin,re:classloading}
12
    at com.google.common.collect.Iterators$6.transform(Iterators.java:829) ~[guava-31.1-jre.jar%2374!/:?] {}
13
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-31.1-jre.jar%2374!/:?] {}
14
    at com.google.common.collect.Iterators.addAll(Iterators.java:367) ~[guava-31.1-jre.jar%2374!/:?] {}
15
    at com.google.common.collect.Lists.newArrayList(Lists.java:146) ~[guava-31.1-jre.jar%2374!/:?] {}
16
    at com.google.common.collect.Lists.newArrayList(Lists.java:132) ~[guava-31.1-jre.jar%2374!/:?] {}
17
    at net.minecraft.nbt.ListTag.m_6426_(ListTag.java:325) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
18
    at net.minecraft.nbt.ListTag.m_6426_(ListTag.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
19
    at com.google.common.collect.Maps$9.transformEntry(Maps.java:2117) ~[guava-31.1-jre.jar%2374!/:?] {}
20
    at com.google.common.collect.Maps$12.getValue(Maps.java:2165) ~[guava-31.1-jre.jar%2374!/:?] {}
21
    at java.util.HashMap.putMapEntries(HashMap.java:513) ~[?:?] {}
22
    at java.util.HashMap.<init>(HashMap.java:484) ~[?:?] {}
23
    at com.google.common.collect.Maps.newHashMap(Maps.java:258) ~[guava-31.1-jre.jar%2374!/:?] {}
24
    at net.minecraft.nbt.CompoundTag.m_6426_(CompoundTag.java:439) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:mixin,re:classloading}
25
    at net.minecraft.world.item.ItemStack.m_41777_(ItemStack.java:430) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
26
    at net.minecraft.world.item.ItemStack.m_255036_(ItemStack.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
27
    at net.minecraft.world.level.storage.loot.LootTable.m_287134_(LootTable.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
28
    at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
29
    at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
30
    at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
31
    at net.minecraft.world.level.storage.loot.entries.LootItem.m_6948_(LootItem.java:33) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
32
    at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
33
    at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading,pl:accesstransformer:B}
34
    at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:94) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading,pl:accesstransformer:B}
35
    at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:85) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
36
    at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:117) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
37
    at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23119!/:?] {re:classloading}
38
    at vectorwing.farmersdelight.common.loot.modifier.AddLootTableModifier.doApply(AddLootTableModifier.java:42) ~[FarmersDelight-1.20.1-1.2.2.jar%23113!/:1.20.1-1.2.2] {re:classloading}
39
    at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.2.0-universal.jar%23124!/:?] {re:classloading}
40
    at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1186) ~[forge-1.20.1-47.2.0-universal.jar%23124!/:?] {re:classloading}

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by edgarogh** [comment]
The crash can be reproduced with just FD 1.2.2 and no other mod, but the latest version of FD doesn't crash anymore.

**Comment by vectorwing** [comment]
Correct, this was a critical bug in version 1.2.2, which was fixed on hotfix 1.2.2a and above.
Please update to version 1.2.3 to resolve it.
