### ISSUE TITLE
[1.16.4] Bucket on rice crop bug

### ISSUE THREAD

**Issue by Mikeliro** [vectorwing/FarmersDelight#92]
Description:
Click with a bucket on the submerged part of the rice crop the game crash

Steps to reproduce:
Click with a bucket on the submerged part of the rice crop

Expected behavior:
Take the water and break the rice crop

Mod list:
forge-1.16.4-35.1.7
farmersdelight-1.16.3-0.2.4a
Xaeros Minimap 20.28.1
Jei 7.6.0.58

Crash Report:
`
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{farmersdelight:rice_crop}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:classloading}
	at net.minecraft.block.IWaterLoggable.func_204508_a(SourceFile:32) ~[?:?] {re:classloading}
	at net.minecraft.item.BucketItem.func_77659_a(BucketItem.java:70) ~[?:?] {re:classloading,xf:fml:forge:bucketitem}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.7.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/250702170.call(Unknown Source) [forge-1.16.4-35.1.7.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
`

**Comment by vectorwing** [comment]
Just tested it locally. Can confirm it happens as early as 1.15.2 when using buckets on the rice crop. I had removed its `waterlogged` state as neither seagrass nor kelp use it... might have left something behind.

I'll fix it on this upcoming release. Thank you for reporting!

**Comment by vectorwing** [comment]
Fixed on commit f75ed77. The behavior is now the same as seagrass and kelp (a bucket cannot take the liquid from them).
