### ISSUE TITLE
[1.21] CME in ItemProperties registration

### ISSUE THREAD

**Issue by lcy0x1** [vectorwing/FarmersDelight#963]
### Minecraft version

1.21.1

### Farmer's Delight version

1.2.4

### NeoForge version

21.1.4

### Description

https://github.com/vectorwing/FarmersDelight/blob/1.21/src/main/java/vectorwing/farmersdelight/client/event/ClientSetupEvents.java#L32

I believe ItemProperty registration is not thread safe and needs to be enqueued using `event.enqueueWork(()->{…});`

### Steps to reproduce

Happens at random during client startup.

### Mod list

Modlist should not be relevant for this issue.

### Logs

```java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:61)
	at TRANSFORMER/farmersdelight@1.2.4/vectorwing.farmersdelight.client.event.ClientSetupEvents.init(ClientSetupEvents.java:32)```

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Fixed on commit 4eea661. Thanks for pointing it out! 👍
